workflows:
  android-workflow:
    name: Patmusic Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build APK
        script: |
          gradle assemble

    artifacts:
      - app/build/outputs/apk/**/*.apk

    publishing:
      email:
        recipients:
          - patricksynnah@gmail.com
        notify:
          success: true
          failure: true
